name: CI
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1-alpine
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.80.0
        with:
          ruby-version: 2.7.2

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: |
          bundle install

      - name: Setup database
        env:
          RAILS_ENV: test
          DISABLE_SPRING: 1
          DATABASE_URL: "postgres://postgres@localhost:5432/github_search_test"
        run: |
          bundle exec bin/rails db:test:prepare

      - name: Build and test with rspec
        env:
          RAILS_ENV: test
          WITH_COVERAGE: true
          DATABASE_URL: "postgres://postgres@localhost:5432/github_search_test"
        run: |
          bundle exec rspec spec

      - name: Run RuboCop
        run: |
          bundle exec rubocop

      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
